name: Create pull-request between branches with resolution
description: prepare a pull-request from one branch to another with custom resolution strategy
inputs:
  source-branch:
    required: true
    description: source branch
  target-branch:
    required: true
    description: target branch

outputs:
  pr-url:
    description: url of the created pull-request
    value: ${{ steps.prepare-pr.outputs.pr-url }}

runs:
  using: "composite"
  steps:
      #- name: Clean pr temporary branch if already exists
      #  uses: ./.github/actions/delete-branch
      #  with:
      #    branch: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}

        #- name: Run copy branch action
        #  uses: ./.github/actions/branch-cutoff-action
        #  with:
        #    source-branch: ${{ inputs.source-branch }}
        #    target-branch: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}

        #    - name: Checkout code
        #      uses: actions/checkout@v4
        #      with:
        #          ref: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}
        #
    - name: Add repository to git safe directories to avoid dubious ownership issue
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash

    - name: Config user
      run: |
         git config --global user.email "git-action@gooddata.com"
         git config --global user.name "git-action"
      shell: bash

    - name: Prepare pr with attempt to resolve conflicts
      run: |
          # attempt to merge, check conflicts, if only in certain files, use $TARGET_BRANCH to resolve
          git fetch origin
          git checkout $SOURCE_BRANCH_RAW
          git checkout -b $SOURCE_BRANCH
          git merge --allow-unrelated-histories --verbose origin/$TARGET_BRANCH || true
          conflicting_files=$(git diff --name-only --diff-filter=U)
          echo "conflicts:"
          echo $conflicting_files
          exit 1
          expected_files=("package.json" "version-policies.json")
          unexpected_conflict="false"

          for file in $conflicting_files
          do
            if [[ ! " ${expected_files[@]} " =~ " ${file} " ]]; then
              unexpected_conflict="true"
              break
            fi
          done


          if [ "$unexpected_conflict" = "true" ]; then
            echo "Skipping automated merge, there are unexpected conflicts"
            exit
          fi

          # perform back-merge resolution
          for file in $conflicting_files
          do
              git checkout --theirs $file
              git add $file
          done
          git commit --no-verify -m "Resolved merge conflicts to match $TARGET_BRANCH"
          git push origin $SOURCE_BRANCH
      env:
          SOURCE_BRANCH_RAW: ${{ inputs.source-branch }}
          SOURCE_BRANCH: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}
          TARGET_BRANCH: ${{ inputs.target-branch }}
      shell: bash

    - uses: actions/github-script@v7
      id: prepare-pr
      env:
          SOURCE_BRANCH: ${{ inputs.source-branch }}-to-${{ inputs.target-branch }}
          TARGET_BRANCH: ${{ inputs.target-branch }}
      with:
        script: |
          const { SOURCE_BRANCH, TARGET_BRANCH } = process.env

          const response = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Merge ${SOURCE_BRANCH} into ${TARGET_BRANCH}`,
            head: SOURCE_BRANCH,
            base: TARGET_BRANCH,
          });

          const prUrl = response.data.html_url;
          core.setOutput('pr-url', prUrl);
        result-encoding: string
