# (C) 2024 GoodData Corporation

name: Prepare commits after code drop

on:
  workflow_dispatch:
      inputs:
        password:
          description: Password for releasing
          required: true

jobs:
  prepare-branch:
    # have dummy password to prevent accidental run
    if: github.event.inputs.password == 'dummy'

    # runs-on: [infra1-small]
    # container:
    #   image: 020413372491.dkr.ecr.us-east-1.amazonaws.com/3rdparty/library/node:18
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run copy branch action
        uses: ./.github/actions/branch-cutoff-action
        with:
          source-branch: 'master'
          target-branch: 'release-2'

  prepare-versions-release:
    needs: prepare-branch
    uses: ./.github/workflows/rw-bump-version.yml
    with:
        source-branch: 'release-2'
        bump: 'prerelease'
        prerelease-id: 'beta'

  prepare-versions-master:
    needs: prepare-branch
    uses: ./.github/workflows/rw-bump-version.yml
    with:
        source-branch: 'master'
        bump: 'preminor'
        prerelease-id: 'alpha'

        #  slack-notification:
        #    runs-on: ubuntu-latest
        #    needs: [prepare-versions-release, prepare-versions-master]
        #    steps:
        #      - name: Inform to slack
        #        uses: slackapi/slack-github-action@v1.23.0
        #        with:
        #            channel-id: '#pb-test-gh-action'
        #            slack-message: "Code drop finished"
        #            env:
        #            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
