# (C) 2024 GoodData Corporation

name: Prepare commits after code drop

on:
  workflow_dispatch:
      #    inputs:
      #      version:
      #        type: choice
      #        description: Type of the current release being branched
      #        options:
      #        - major
      #        - minor

jobs:
  prepare-version:
    # runs-on: [infra1-small]
    # container:
    #   image: 020413372491.dkr.ecr.us-east-1.amazonaws.com/3rdparty/library/node:18
    runs-on: ubuntu-latest
    #image: node:18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run copy branch action
        uses: ./.github/actions/branch-cutoff-action
        with:
          source-branch: 'master'
          target-branch: 'release-1'
      - name: Bump version in master branch
        uses: ./.github/actions/bump-version
        with:
          source-branch: 'master'
          bump: 'preminor'
          prerelease-id: 'alpha'
      - name: Bump version in release branch
        uses: ./.github/actions/bump-version
        with:
          source-branch: 'release-1'
          bump: 'prerelease'
          prerelease-id: 'beta'
      - name: Simple message
        shell: bash
        run: |
            echo "Finished with"
