name: TEST - check
on:
  workflow_dispatch:
      inputs:
        source-branch:
          description: source
          required: true
        target-branch:
          description: target
          required: true

jobs:
  test:
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run test
        id: test
        uses: ./.github/actions/prepare-merge
        with:
          source-branch: ${{ inputs.source-branch }}
          target-branch: ${{ inputs.target-branch }}
      - name: Run output
        run: echo The pr created here ${{ steps.test.outputs.pr-url }}
